# Generated by Django 4.2.30 on 2026-05-22 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=20)),
                ('capacity_kg', models.FloatField(default=1000.0)),
                ('is_active', models.BooleanField(default=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataMiningReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('insight', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=100)),
                ('trend', models.CharField(default='stable', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PlasticType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('PET', 'PET - Polyethylene Terephthalate'), ('HDPE', 'HDPE - High-Density Polyethylene'), ('PVC', 'PVC - Polyvinyl Chloride'), ('LDPE', 'LDPE - Low-Density Polyethylene'), ('PP', 'PP - Polypropylene'), ('PS', 'PS - Polystyrene'), ('OTHER', 'Other Plastics')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('recyclable', models.BooleanField(default=True)),
                ('hazard_level', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WasteSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitter_name', models.CharField(max_length=200)),
                ('submitter_email', models.CharField(max_length=200)),
                ('submitter_phone', models.CharField(blank=True, max_length=20)),
                ('weight_kg', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('collected', 'Collected'), ('processing', 'Processing'), ('recycled', 'Recycled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('points_earned', models.IntegerField(default=0)),
                ('collection_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eplastic.collectioncenter')),
                ('plastic_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eplastic.plastictype')),
            ],
        ),
        migrations.CreateModel(
            name='RecyclingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('total_collected_kg', models.FloatField(default=0)),
                ('total_recycled_kg', models.FloatField(default=0)),
                ('co2_saved_kg', models.FloatField(default=0)),
                ('energy_saved_kwh', models.FloatField(default=0)),
                ('submissions_count', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('month', 'year')},
            },
        ),
    ]
